[bar.default]
capsule = true
center = []
end = [
    "media",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "clock",
    "session"
]
margin_ends = 0
position = "top"
radius = 0
shadow = false
start = [ "launcher", "control-center", "wallpaper", "workspaces", "active_window" ]

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "command"
    enabled = true
    timeout = 660.0
    command = "wlopm --off '*'"
    resume_command = "wlopm --on '*'"

[osd.kinds]
keyboard_layout = false
media = false

[shell.panel]
open_near_click_control_center = true

[widget.clock]
format = "{:%-l:%M %p}"
